### ISSUE TITLE
Graphical User Interface for Tensorflow

### ISSUE THREAD

**Issue by riya-17** [sharmalab/Emory-BMI-GSoC-2019#2]
Hello @pradeeban @lastlegion ,

I am really interested in this issue and would like to contribute to it. Can anyone please help me get more details regarding this idea and how can I get started with this.

Thank you

**Comment by pradeeban** [comment]
Hi Riya,
Thanks for your interest. The GSoC selected organizations will be announced on February 26 12:00 UTC. If Emory BMI is selected as a mentoring organization this year, we will invite all our interested student applicants to our Slack room. You may send us an email for us to add you to the Slack channel by the 26th.

In the meantime, you may focus on getting familiarized with the technologies listed. Feel free to contact the respective mentors, if you have any specific questions on the project idea.

**Comment by riya-17** [comment]
Hi,

Here is my e-mail id - riyad17031998@gmail.com.

Thank you for your response. I will go through the technologies. How can I contact the Mentors?

**Comment by pradeeban** [comment]
The mentors' email addresses are included under each project. I have added you to our slack. 

You can use the Slack to discuss project ideas when the mentors are online. It will be helpful if you are more specific in your questions when you contact the mentors.

**Comment by riya-17** [comment]
Ok. Thanks :)
